config/routes.rb
Rails.application.routes.draw do

  root "welcome#about"

#users and users project paths
  resources :users do
    resources :projects, except: [:index]
    post '/projects/:id/comments', to: 'project_comments#create', as: :comment_project
    get '/projects/:id/comments', to: 'project_comments#index'
    delete '/projects/:id', to: 'projects#delete', as: :delete_project
  end

  get '/active_projects', to: 'projects#index'
  post '/back_project/:id', to: 'backed_projects#back_project', as: :back_project
  get '/users/:user_id/projects', to: 'projects#redirect'

  resources :categories, only:[:index, :show]

  get '/auth/github/callback' => 'sessions#create'

  get "/login", to: 'sessions#new', as: 'login'
  post "/logging_in", to: 'sessions#create', as: 'logging_in'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :projects
  has_many :backed_projects
  has_many :projects_backed, through: :backed_projects, source: 'project'
  has_many :project_comments
  validates :username, presence: true
  validates :email, presence: true

  def add_project(project)
    if self.projects_backed.where(id: project.id).empty?
      BackedProject.create(user: self, project: project)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update]
  before_action :access_user, only:[:edit, :update]

  def new
    if logged_in?
      redirect_to user_path(current_user), flash:{notice: "already logged in!"}
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:password] == params[:password_confirmation] && @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @user, status: 200}
    end 
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to @user, flash:{notice: "Your account has been successfully updated!"}
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email)
  end

  def set_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to active_projects_path, flash:{alert: "That user does not exist."}
  end

  def access_user
    @user = User.find_by(id: params[:id])
    unless current_user == @user
      redirect_to active_projects_path, flash:{alert: "You don't have access to that."}
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def correct_user(user)
    user == current_user
  end

  def guest_user(user)
    user != current_user
  end

  def backed_user(user, project)
    user.projects_backed.include?(project) if user 
  end

end

app/views/users/_edit_form.html.erb
<%= form_for user do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%=f.label :username%>
    <%=f.text_field :username%>
  <div>

  <div>
    <%=f.label :email%>
    <%=f.text_field :email%>
  <div>

  <div>
    <%=f.label :phone_number, "Phone Number (Optional)"%>
    <%=f.text_field :phone_number%>
  <div>

  <div class="action">
    <%=f.submit "Submit"%>
  </div>

<% end %>

app/views/users/_form.html.erb
<%= form_for user do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%=f.label :username%>
    <%=f.text_field :username%>
  <div>

  <div>
    <%=f.label :password%>
    <%=f.password_field :password%>
  <div>

  <div>
    <%=f.label :email%>
    <%=f.text_field :email%>
  <div>

  <div>
    <%=f.label :phone_number, "Phone Number (Optional)"%>
    <%=f.text_field :phone_number%>
  <div>

  <div class="action">
    <%=f.submit "Create Account"%>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Edit this User </h1>

<%=render partial: 'edit_form', locals: {user: @user}%>

app/views/users/new.html.erb
 <h2> Welcome to the family, please sign up here! </h2>

 <%=render partial: 'form', locals: {user: @user}%>

<%= link_to "Back", root_path %>

app/views/users/show.html.erb
<h2> <%= @user.username %>'s projects</h2>

<% if @user.projects.empty? %>
  You currently have no projects, please click <%= link_to "here", new_user_project_path(@user)%> to add one!
<% else %>
  <table>
    <tr>
      <th>Project Name</th>
      <th>Active?</th>
      <th>More</th>
    </tr>
<% @user.projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, user_project_path(@user, project) %></td>
      <td><%= project.active%></td>
      <td><button class="js-more" data-uid="<%=@user.id%>" data-id="<%= project.id %>">Details..</button></td>
    </tr>
    <% end %>
  </table>

<% end %>
<div id='project-display'>
</div>

<% if correct_user(@user) %>
  <p><%= link_to "Add new project", new_user_project_path(@user)%></p>
  <br>
  <b> Backed Projects: </b>
  <ul>
    <%@user.projects_backed.each do |project|%>
      <li><%=link_to project.name, user_project_path(project.user, project)%></li>
    <% end %>
  </ul>
<% end %>