config/routes.rb
Rails.application.routes.draw do

  root "welcome#about"

#users and users project paths
  resources :users do
    resources :projects, except: [:index]
    post '/projects/:id/comments', to: 'project_comments#create', as: :comment_project
    get '/projects/:id/comments', to: 'project_comments#index'
    delete '/projects/:id', to: 'projects#delete', as: :delete_project
  end

  get '/active_projects', to: 'projects#index'
  post '/back_project/:id', to: 'backed_projects#back_project', as: :back_project
  get '/users/:user_id/projects', to: 'projects#redirect'

  resources :categories, only:[:index, :show]

  get '/auth/github/callback' => 'sessions#create'

  get "/login", to: 'sessions#new', as: 'login'
  post "/logging_in", to: 'sessions#create', as: 'logging_in'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :project_categories
  has_many :categories, through: :project_categories
  has_many :backed_projects
  has_many :backed, through: :backed_projects, source: 'user'
  has_many :project_comments
  validates :name, :description, presence: true
  accepts_nested_attributes_for :categories
  scope :active_projects, -> {where(active: true)}

  def categories_attributes=(category_attributes)
    category_attributes.values.each do |category_attribute|
      if category_attribute[:name].present?
        category = Category.find_or_create_by(category_attribute)
        if !self.categories.include?(category)
          self.categories << category
        end
      end
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_user_and_project, only:[:show, :edit, :update, :destroy]
  before_action :allowed_user, only:[:edit, :destroy]

  def index
    @projects = Project.active_projects
    respond_to do |format|
      format.html{render :index}
      format.json{render json: @projects, status: 200}
    end
  end

  def new
    @user = User.find_by(id: params[:user_id])
    @project = @user.projects.new(user_id: params[:user_id])
  end

  def create
    @user = User.find_by(id: params[:user_id])
    @project = Project.new(project_params)
    if @project.save
      redirect_to user_project_path(@project.user_id, @project)
    else
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html{render :show}
      format.json{render json: @project, status: 200}
    end
  end

  def edit
  end

  def update
    @project.update(project_params)
    redirect_to user_project_path(@user, @project), flash: {notice: "Your project has been updated!"}
  end

  def destroy
    @project.destroy
    redirect_to root_path, flash:{notice: "Your project has been deleted"}
  end

  def redirect
    redirect_to new_user_project_path(params[:user_id])
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :city, :user_id, :active, :state, category_ids:[], categories_attributes:[:name])
  end

  def set_user_and_project
    if params[:user_id] && User.exists?(params[:user_id])
      @user = User.find_by(id: params[:user_id])
      @project = @user.projects.find_by(id: params[:id])
      if @project.nil?
        redirect_to active_projects_path, flash:{alert: "That project does not exist."}
      end
    else
      redirect_to active_projects_path, flash:{alert: "That user does not exist."}
    end
  end

  def allowed_user
    @project = Project.find_by(id: params[:id])
    unless current_user == @project.user
      redirect_to active_projects_path, flash:{alert: "You don't have access to that."}
    end
  end



end

app/helpers/projects_helper.rb
module ProjectsHelper

  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
end


  def edit_project(user, project)
    link_to "Edit Project", edit_user_project_path(user, project), id: 'edit-project'
  end

  def delete_project(user, project)
    link_to "Delete Project", user_delete_project_path(user, project), id: 'delete-project', method: :delete, confirm: "Are you sure?"
  end

end

app/views/projects/_form.html.erb
<%= form_for [@user, @project] do |f| %>
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h4>

    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <%= f.hidden_field :user_id %>

  <div>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>

    <div>
      <%= f.label :state %>
      <%= f.select(:state, options_for_select(us_states)) %>
    </div>

    <div>
      <%= f.label :active, "Active Project?" %>
      <%= f.check_box :active %>
    </div>

    <p>Choose some Categories!</p>

    <div>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name%>
    </div>

    <p> Or create your own! </p>

    <div>
      <%= f.fields_for :categories, @project.categories.build do |categories_fields| %>
        <%= categories_fields.label :name, "Create a new category" %>
        <%= categories_fields.text_field :name %>
      <% end %>
    </div>

    <div class="label">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, :cols => 80, :rows => 15 %>
    </div>

    <div class="actionButtons">
      <%= f.submit %>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<h1> Edit <%= @project.name %> </h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>All Projects!</h1>

<table>
  <tr>
    <th>Project Name</th>
    <th>Project Creator</th>
  </tr>
  <% @projects.each do |project| %>
    <tr>
      <th><%= link_to project.name, user_project_path(project.user_id, project) %></th>
      <th><%= link_to project.user.username, user_path(project.user) %> </th>
    </tr>
  <% end %>
</table>

app/views/projects/new.html.erb
<h1> Create your project! </h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="title" id="project_title">
  <h1><%=@project.name%></h1>
</div>

<div>
  <center><%=button_to "Back this project",back_project_path(@project.id) if guest_user(@user)%></center>
</div>

<div>
  <center>
    <%if correct_user(@user) %>
      <%= edit_project(@user, @project)%> - <%= delete_project(@user, @project) %>
    <% end %>
  </center>
</div>

<div class="project-location">
  <h4>Project location: <%=@project.city%>, <%=@project.state%></h4>
</div>
<div class="project-description">
  <h3>Description:</h3>
  <p><%=@project.description%></p>
</div>


<div class="categories">
  <h4>Relevant Categories:</h4>
    <ul class="category-list">
        <% @project.categories.each do |category| %>
          <li class="category-item"> <%=link_to category.name, category_path(category)%> </li>
        <% end %>
    </ul>
</div>

<div>
  <%if backed_user(current_user, @project) %>
    <p> Contact this user to collaborate: <%=@user.email%></p>
  <% end %>
</div>

<div class="js-next" data-uid="<%=@user.id%>" data-id="<%=@project.id%>">
  <button class="next-button">Next Project</button>
</div>

<div class="comment-form">
  <%=form_for(ProjectComment.new, url: user_comment_project_path(@user, @project)) do |f|%>
    <%=f.hidden_field :user_id, value: current_user.id if current_user%>
    <%=f.hidden_field :project_id, value: @project.id, id: 'hidden-projectId' %>
    <%= f.text_area :comment, class: 'comment-box'%> <br>
    <%= f.submit "Submit Comment", id: 'comment-button' %>
  <% end %>
</div>

<a href=# class="show-comments">Show Comments</a>
<div class="comments">
  <ol class="comment-list">
  </ol>
</div>