config/routes.rb
Rails.application.routes.draw do

  root "welcome#about"

#users and users project paths
  resources :users do
    resources :projects, except: [:index]
    post '/projects/:id/comments', to: 'project_comments#create', as: :comment_project
    get '/projects/:id/comments', to: 'project_comments#index'
    delete '/projects/:id', to: 'projects#delete', as: :delete_project
  end

  get '/active_projects', to: 'projects#index'
  post '/back_project/:id', to: 'backed_projects#back_project', as: :back_project
  get '/users/:user_id/projects', to: 'projects#redirect'

  resources :categories, only:[:index, :show]

  get '/auth/github/callback' => 'sessions#create'

  get "/login", to: 'sessions#new', as: 'login'
  post "/logging_in", to: 'sessions#create', as: 'logging_in'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :project_categories
  has_many :projects, through: :project_categories

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end


end

app/views/categories/index.html.erb
<h1> All Categories </h1>

<ul class="category-list">
<% @categories.each do |category| %>
  <li class="category-item"><%=link_to category.name, category_path(category)%></li>
<% end %>
</ul>
<a href=# class="more-categories">Load More</a>

app/views/categories/show.html.erb
<h1>All projects under <%=@category.name%></h1>

<ul>
<%@category.projects.each do |project|%>
  <li><%=link_to project.name, user_project_path(project.user, project)%></li>
<% end %>
</ul>

<%= link_to "Categories Index", categories_path %>