config/routes.rb
Rails.application.routes.draw do

  root "welcome#about"

#users and users project paths
  resources :users do
    resources :projects, except: [:index]
    post '/projects/:id/comments', to: 'project_comments#create', as: :comment_project
    get '/projects/:id/comments', to: 'project_comments#index'
    delete '/projects/:id', to: 'projects#delete', as: :delete_project
  end

  get '/active_projects', to: 'projects#index'
  post '/back_project/:id', to: 'backed_projects#back_project', as: :back_project
  get '/users/:user_id/projects', to: 'projects#redirect'

  resources :categories, only:[:index, :show]

  get '/auth/github/callback' => 'sessions#create'

  get "/login", to: 'sessions#new', as: 'login'
  post "/logging_in", to: 'sessions#create', as: 'logging_in'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/views/layouts/_navbar.html.erb
<nav>
  <%if logged_in?%>
    <small class="signed-in">Signed in as <%=current_user.username%></small>&nbsp;
    <a class="navbar-brand" href="<%= user_path(current_user) %>"/>Home</a>&nbsp;
    <a class="navbar-brand" href="/logout" data-method="delete"/>Signout</a>&nbsp;
  <% elsif !logged_in?%>
    <a class="navbar-brand" href="<%= login_path %>"/>Login</a>&nbsp;
    <a class="navbar-brand" href="<%= new_user_path %>"/>Sign up</a>&nbsp;
  <% end %>
  <a class="navbar-brand" href="<%= active_projects_path %>"/>Community's Projects</a>&nbsp;
  <a class="navbar-brand" href="<%= categories_path %>"/>Project Categories</a>&nbsp;
  <a class="navbar-brand" href="<%= root_path %>"/>About Prive</a>&nbsp;
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projekt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'normalize', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'grid', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,300i,400" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="transbox">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <a href="http://www.freepik.com" id="credit">Designed by Tirachard / Freepik</a>
  </body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>